### ISSUE TITLE
Problem with the step attribute

### ISSUE THREAD

**Issue by jonycelio** [Wildhoney/ngRangeSlider#8]
I was trying to use this module for a range of product prices, and prices are decimal. For this, I used the step that is already in the module-inclusive, however it does not work. I can put any step that will not work. I even checked the HTML itself and it was written in the step I typed, but does not help. Am I doing something wrong or is it a problem that module?

**Comment by Wildhoney** [comment]
It was a problem with the module, Jonathan. Apologise for that. It should be fixed in https://github.com/Wildhoney/ngRangeSlider/commit/0516ba0a0f8335901e0865cac24c7052df7ac2e8 if you update the module to `v0.1.12`. Please let me know if it works for you :+1:

**Comment by jonycelio** [comment]
It works, thank you, but all input range thumbs now always start at the beginning, even setting the scopes.

**Comment by Wildhoney** [comment]
Hmm... That's odd! [In the example](http://ng-range-slider.herokuapp.com/) they don't start at the beginning. Which browser are you using? I've [setup a JSFiddle](http://jsfiddle.net/oqeff08q/) for this, so hopefully we can replicate.

**Comment by jonycelio** [comment]
You're right. Then have to be my code. I will check...

**Comment by Wildhoney** [comment]
Please update the ticket once you've found the culprit +1
